name: AranarthCore
version: 1.0
authors: [Aearost]
main: com.aearost.aranarthcore.AranarthCore
api-version: 1.20
depend: [mcMMO]
description: A core plugin to incorporate any features we desire into our Minecraft world
loadbefore: [mcMMO]
commands:
   ac:
      description: All underlying commands regarding the plugin